apiVersion: v1
kind: Namespace
metadata:
  name: code-server-01
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: code-server-01
  namespace: code-server-01
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: code-server-01.vk8s-01-proxy.in.llycloud.com
    http:
      paths:
      - backend:
          serviceName: code-server-01
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: code-server-01
 namespace: code-server-01
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server-01
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server-01
  name: code-server-01
  namespace: code-server-01
spec:
  selector:
    matchLabels:
      app: code-server-01
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-01
    spec:
      containers:
      - image: codercom/code-server:latest
        imagePullPolicy: Always
        name: code-server-01
        env:
        - name: PASSWORD
          value: "123.com"
        volumeMounts:
          - name:  code-server-01-storage
            mountPath:  /home/coder/project
      volumes:
        - name:  code-server-01-storage
          persistentVolumeClaim:
            claimName: code-server-01-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-01-pv-claim
  namespace: code-server-01
  labels:
    app: code-server-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi