apiVersion: v1
kind: Namespace
metadata:
  name: code-server-02
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: code-server-02
  namespace: code-server-02
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # - host: code-server-02.vk8s-01-proxy.in.llycloud.com
  - host: code-server-02.172.16.0.213.xip.io
    http:
      paths:
      - backend:
          serviceName: code-server-02
          servicePort: 80
  - host: code02.dev.vmv.re
    http:
      paths:
      - backend:
          serviceName: code-server-02
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: code-server-02
 namespace: code-server-02
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server-02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server-02
  name: code-server-02
  namespace: code-server-02
spec:
  selector:
    matchLabels:
      app: code-server-02
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-02
    spec:
      containers:
      - image: akide/oop-project-code-server-docker:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        name: code-server-02
        volumeMounts:
          - name:  code-server-02-storage
            mountPath:  /home/coder/project
      volumes:
        - name:  code-server-02-storage
          persistentVolumeClaim:
            claimName: code-server-02-pv-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-02-pv-claim
  namespace: code-server-02
  labels:
    app: code-server-02
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi